#!/bin/bash

p[1]="0 1"
p[2]="0 2"
p[3]="0 3"
p[4]="1 2"
p[5]="2 3"
p[6]="1 3"
for j in {1..6}; do
  echo test $j
  for i in ${p[$j]}; do
    (dd if=/dev/zero of=zeroes$i bs=262144K count=1 && sync) &
    p=$(ps -ef | grep zeroes$i | grep dd | awk '{print $2;}')
    ionice -c $i -p $p
    echo "ionice -c $i -p $p"
  done
  sleep 10
done
rm zeroes{0..3}

exit
